name: Assemble AAB Bundle File

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true
    inputs:
      MODULE_NAME:
        description: 'Which module you need to run this flow on....'
        type: string
        required: true

    outputs:
      abb_folder_id:
        description: "uploaded abb folder name"
        value: ${{ jobs.assemble.outputs.folder_name }}
jobs:
  assemble:
    name: Assemble Android Module AAB
    runs-on: ubuntu-latest
    env:
      ABB_FOLDER_NAME: "assemble_module"
    outputs:
      folder_name: ${{ steps.assign_abb_folder.outputs.folder_name }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

#      - name: Print Gradle variable
#        run: echo "::set-env name=MY_VARIABLE::$(./gradlew printVariable | grep '^MY_VARIABLE=' | cut -d'=' -f2)"
#
#      - name: Use Gradle variable
#        run: echo $MY_VARIABLE

        #BUILD  CACHING
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

          #SETUP JAVA
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x ./gradlew

      - name: Build AAB âš™ï¸ðŸ› 
        run: |
          ./gradlew ${{ inputs.MODULE_NAME }}:bundleRelease
          echo "my_variable=${MY_VARIABLE}" > gradle.properties
        
      - name: Display Variable
        run: |
          source gradle.properties
          echo "The variable is: $my_variable"

      - name: Upload Assemble Module AAB
        # Upload report to ubuntu server to be used on another action...
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ABB_FOLDER_NAME }}
          path: ${{ inputs.MODULE_NAME }}/build/outputs/bundle/release/**-release.aab
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Assign ABB FOLDER AS OUTPUT
        id: assign_abb_folder
        run: echo "folder_name=$ABB_FOLDER_NAME" >> $GITHUB_OUTPUT

      - name: Ping Slack Assemble Module AAB Failed
        uses: someimportantcompany/github-actions-slack-message@v1
        if: failure()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            *Assemble Android-module AAB failed*
          color: failure

